### ISSUE TITLE
v.1.3.0 - Wrong Version displayed (perhaps only number/tag?)

### ISSUE THREAD

**Issue by l0ader3000** [Section214/franz-devrant#1]
Hello!

In Franz, if clicked on the "Franz Integration" of the devRant-plugin it still reads "Version 1.2.0" although I double checked, that I downloaded and clean-installed version 1.3.0
Also the "What's New"-Link links to release 1.2.0 in Github.

**Comment by evertiro** [comment]
That'd be my fault! I was super tired when I tagged it... forgot to actually push the final changeset!
